<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="Cloudbreak login" timestamp="2016-02-11T14:31:18" hostname="localhost" time="18.305" errors="0" tests="0" skipped="0" disabled="0" failures="0">
 </testsuite>
 <testsuite name="Cloudbreak login.launch application" timestamp="2016-02-11T14:31:18" hostname="localhost" time="18.305" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="Cloudbreak login.launch application" name="should be at the Dashboard page" time="18.269" />
  <testcase classname="Cloudbreak login.launch application" name="should see default blueprints" time="0.032">
   <failure type="toEqual" message="Expected 4 to equal 3."><![CDATA[Error: Failed expectation
    at /Users/aszegedi/prj/uluwatutests/uluwatu-e2e-protractor/tests/LoginSpec.js:17:23
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:401:9)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Testing Blueprints on Dashboard" timestamp="2016-02-11T14:31:36" hostname="localhost" time="7.457" errors="0" tests="0" skipped="0" disabled="0" failures="0">
 </testsuite>
 <testsuite name="Testing Blueprints on Dashboard.Create a new blueprint" timestamp="2016-02-11T14:31:36" hostname="localhost" time="7.457" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="Testing Blueprints on Dashboard.Create a new blueprint" name="autotest-multi-node-hdfs-yarn" time="7.457" />
 </testsuite>
 <testsuite name="Testing Credentials on Dashboard" timestamp="2016-02-11T14:31:44" hostname="localhost" time="13.159" errors="0" tests="0" skipped="0" disabled="0" failures="0">
 </testsuite>
 <testsuite name="Testing Credentials on Dashboard.Create a new credential" timestamp="2016-02-11T14:31:44" hostname="localhost" time="13.159" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="Testing Credentials on Dashboard.Create a new credential" name="autotest-aws" time="13.155" />
 </testsuite>
 <testsuite name="Cluster testing" timestamp="2016-02-11T14:31:57" hostname="localhost" time="182.426" errors="0" tests="0" skipped="0" disabled="0" failures="0">
 </testsuite>
 <testsuite name="Cluster testing.on a new cluster" timestamp="2016-02-11T14:31:57" hostname="localhost" time="182.426" errors="0" tests="5" skipped="0" disabled="0" failures="1">
  <testcase classname="Cluster testing.on a new cluster" name="AWS credential should be selected" time="0.307" />
  <testcase classname="Cluster testing.on a new cluster" name="AWS cluster should be created" time="8.176" />
  <testcase classname="Cluster testing.on a new cluster" name="AWS cluster should be started" time="0.057" />
  <testcase classname="Cluster testing.on a new cluster" name="AWS cluster should be run" time="167.804">
   <failure type="toBeTruthy" message="Expected false to be truthy."><![CDATA[Error: Failed expectation
    at Object.<anonymous> (/Users/aszegedi/prj/uluwatutests/uluwatu-e2e-protractor/tests/ClusterSpec.js:33:43)
    at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:92:15
    at [object Object].promise.Promise.goog.defineClass.constructor (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1056:7)
    at new wrappedCtr (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:2468:26)
    at controlFlowExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:401:9)]]>
   </failure>
  </testcase>
  <testcase classname="Cluster testing.on a new cluster" name="selected cluster should be terminated" time="6.08" />
 </testsuite>
</testsuites>